### ISSUE TITLE
[Jar] Create script to get executable jar

### ISSUE THREAD

**Issue by MLGMAG** [Tim2313/OrderBook#1]
Create a bash script to compile / package source code.
So that, everyone can run it and use your program.

This feature will made the testing of your application more easier.

Important notes:
- It should be possible to run this script on Linux environment (Windows is not important)
- The script should be package independent.
- Add a note in the README, that will guide other developers to get the jar.
- The script can be placed in the root under the 'script' directory 

Happy path:
1. Clone repository
2. Run script
3. Get the executable Jar
4. Run it

**Comment by Tim2313** [comment]
Fix 0b374fe8e3425fa6cb9283f0a6bc3889e713a16d
